### ISSUE TITLE
Minio default auth signature seems to has been changed

### ISSUE THREAD

**Issue by eizemazal** [kneufeld/minio-put#2]
Thanks for all the code!

I was trying to make bare bone uploads to S3 storage and experimented with curl. But unfortunately the example shell script from the repo did not work for me as of 08/2020 with latest Minio.

After it failed, I uploaded files to Minio using Boto3 Python lib and analyzed traffic with tcpdump, the valid request looked like that:

PUT /upload/s3_logo.png HTTP/1.1
Host: 127.0.0.1:9000
Accept-Encoding: identity
User-Agent: Boto3/1.18.32 Python/3.9.1 Darwin/20.2.0 Botocore/1.21.32
Content-MD5: Y9c3aK4t+uMu+UqBrgOI5A==
Expect: 100-continue
X-Amz-Date: 20210831T092028Z
X-Amz-Content-SHA256: e0b21adee38de3c4ee119f50ae5c2f9f87efdf11486431b2db91e3c94d4e2c76
Authorization: AWS4-HMAC-SHA256 Credential=miniouser/20210831/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=294ea3665ce6668a3b7a7740e567cd857b9bcd3509b7f8dd3f0626a310a4bac0
Content-Length: 3220

<FILE GOES HERE>

It seems that some other signing protocol is used here (maybe possible to change it in Minio though). It does not seem hard to research this protocol and make PUTs with curl, but I will resort to using a library to do uploads...

**Comment by konstantingoretzki** [comment]
Are you sure?
I've tried the Bash script with Minio v2021-12-27T07:23:18Z and it worked flawlessly.

**Comment by eizemazal** [comment]
Sorry for taking a lot of time to play with this and check a minimalistic example. Unfortunately I was busy in my project, and could not reproduce my original set up, but most likely there was a problem on my side.

I just checked it with minio:latest from Docker Hub for ARM64, and after changing https to http in minio-put.sh it worked well (felt lazy to set up SSL in Minio container). So I would like to close the issue and just confirm it works - thank you.
